unit uISelenium;

interface
uses
  uCommon;
  
type
	ISelenium = interface
    ['{A1823B55-C4C1-4191-AA10-48DEC380884D}']
		procedure Start();
		procedure Stop();
    procedure Click(locator: String);
		procedure ClickAndWait(locator: String);
    procedure DoubleClick(locator: String);
		procedure ContextMenu(locator: String);
		procedure ClickAt(locator: String; coordString: String);
		procedure DoubleClickAt(locator: String; coordString: String);
		procedure ContextMenuAt(locator: String; coordString: String);
		procedure FireEvent(locator: String;eventName: string);
		procedure Focus(locator: string);
		procedure KeyPress(locator: String;keySequence: string);
		procedure ShiftKeyDown();
		procedure ShiftKeyUp();
		procedure MetaKeyDown();
		procedure MetaKeyUp();
		procedure AltKeyDown();
		procedure AltKeyUp();
		procedure ControlKeyDown();
		procedure ControlKeyUp();
		procedure KeyDown(locator: String;keySequence: string);
		procedure KeyUp(locator: String;keySequence: string);
		procedure MouseOver(locator: string);
		procedure MouseOut(locator: string);
		procedure MouseDown(locator: string);
		procedure MouseDownAt(locator: String;coordString: string);
		procedure MouseUp(locator: string);
		procedure MouseUpAt(locator: String;coordString: string);
		procedure MouseMove(locator: string);
		procedure MouseMoveAt(locator: String;coordString: string);
		procedure Type_(locator: String;value: string);
		procedure TypeKeys(locator: String;value: string);
		procedure SetSpeed(value: string);
		function GetSpeed(): string;
		procedure Check(locator: string);
		procedure Uncheck(locator: string);
		procedure Select(selectLocator: string; optionLocator: string);
		procedure AddSelection(locator: String;optionLocator: string);
		procedure RemoveSelection(locator: String;optionLocator: string);
		procedure RemoveAllSelections(locator: string);
		procedure Submit(formLocator: string);
		procedure Open(url: string);
		procedure OpenWindow(url: string;windowID: string);
		procedure SelectWindow(windowID: string);
		procedure SelectFrame(locator: string);
		function GetWhetherThisFrameMatchFrameExpression(currentFrameString: string;target: string): boolean;
		function GetWhetherThisWindowMatchWindowExpression(currentWindowString: string;target: string): boolean;
		procedure WaitForPopUp( windowID: string;timeout: string);
		procedure ChooseCancelOnNextConfirmation();
		procedure ChooseOkOnNextConfirmation();
		procedure AnswerOnNextPrompt(answer: string);
		procedure GoBack();
		procedure Refresh();
		procedure Close();
		function IsAlertPresent(): boolean;
		function IsPromptPresent(): boolean;
		function IsConfirmationPresent(): boolean;
		function GetAlert(): string;
		function GetConfirmation(): string;
		function GetPrompt(): string;
		function GetLocation(): string;
		function GetTitle(): string;
		function GetBodyText(): string;
		function GetValue(locator: string): string;
		function GetText(locator: string): string;
		procedure Highlight(locator: string);
		function GetEval(script: string): string;
		function IsChecked(locator: string): boolean;
		function GetTable(tableCellAddress: string): string;
		function GetSelectedLabels(selectLocator: string): ArrayOfString;
		function GetSelectedLabel(selectLocator: string): string;
		function GetSelectedValues(selectLocator: string): ArrayOfString;
		function GetSelectedValue(selectLocator: string): string;
		function GetSelectedIndexes(selectLocator: string): ArrayOfString;
		function GetSelectedIndex(selectLocator: string): string;
		function GetSelectedIds(selectLocator: string): ArrayOfString;
		function GetSelectedId(selectLocator: string): string;
		function IsSomethingSelected(selectLocator: string): boolean;
		function GetSelectOptions(selectLocator: string): ArrayOfString;
		function GetAttribute(selectLocator: string): string;
		function IsTextPresent(pattern: string): boolean;
		function IsElementPresent(locator: string): boolean;
		function IsVisible(locator: string): boolean;
		function IsEditable(locator: string): boolean;
		function GetAllButtons(): ArrayOfString;
		function GetAllLinks(): ArrayOfString;
		function GetAllFields(): ArrayOfString;
		function GetAttributeFromAllWindows(attributeName: String): ArrayOfString;
		procedure Dragdrop(locator: String; movementsString: string);
		procedure SetMouseSpeed(pixels: String);
		function GetMouseSpeed(): double;
		procedure DragAndDrop(locator: String;movementsString: string);
		procedure DragAndDropToObject(locatorOfObjectToBeDragged:String; locatorOfDragDestinationObject: string);
		procedure WindowFocus();
		procedure WindowMaximize();
		function GetAllWindowIds(): ArrayOfString;
		function GetAllWindowNames(): ArrayOfString;
		function GetAllWindowTitles(): ArrayOfString;
		function GetHtmlSource(): String;
		procedure SetCursorPosition(locator: String; position: string);
		function GetElementIndex(locator: string): double;
		function IsOrdered(locator1: string; locator2: string): boolean;
		function GetElementPositionLeft(locator: string): double;
		function GetElementPositionTop(locator: string): double;
		function GetElementWidth(locator: string): double;
		function GetElementHeight(locator: string): double;
		function GetCursorPosition(locator: string): double;
		function GetExpression(expression: String): string;
		function GetXpathCount(xpath: String): double;
		procedure AssignId(locator: String;  identifier: string);
		procedure AllowNativeXpath(allow: String);
		procedure IgnoreAttributesWithoutValue(ignore: String);
		procedure WaitForCondition(script: String; timeout: String);
		procedure SetTimeout(timeout: String);
		procedure WaitForPageToLoad(timeout: String);
		procedure WaitForFrameToLoad(frameAddress: String; timeout: String);
		function GetCookie():  String;
		function GetCookieByName(name: String):  String;
		function IsCookiePresent(name: String): boolean;
		procedure CreateCookie(nameValuePair: String; optionsString: String);
		procedure DeleteCookie(name: String; optionsString: String);
		procedure DeleteAllVisibleCookies();
		procedure SetBrowserLogLevel(logLevel: String);
		procedure RunScript(script: String);
		procedure AddLocationStrategy(strategyName: String; functionDefinition: String);
		procedure CaptureEntirePageScreenshot(filename: String);
		procedure SetContext(context: String);
		procedure AttachFile(fieldLocator: String; fileLocator: String);
		procedure CaptureScreenshot(filename: String);
		procedure ShutDownSeleniumServer();
		procedure KeyDownNative(keycode: String);
		procedure KeyUpNative(keycode: String);
		procedure KeyPressNative(keycode: String);
  end;

implementation

end.
