unit uISelenium_1_0_3;

interface
uses
  uCommon;
  
type
	ISelenium = interface
    ['{A1823B55-C4C1-4191-AA10-48DEC380884D}']
    procedure SetExtensionJs(extensionJs: UTF8String);
    procedure Start(); overload;
    procedure Start(optionsString: UTF8String); overload;
		procedure Stop();
    procedure Click(locator: UTF8String);
		procedure ClickAndWait(locator: UTF8String);
    procedure DoubleClick(locator: UTF8String);
		procedure ContextMenu(locator: UTF8String);
		procedure ClickAt(locator: UTF8String; coordString: UTF8String);
		procedure DoubleClickAt(locator: UTF8String; coordString: UTF8String);
		procedure ContextMenuAt(locator: UTF8String; coordString: UTF8String);
		procedure FireEvent(locator: UTF8String;eventName: UTF8String);
		procedure Focus(locator: UTF8String);
		procedure KeyPress(locator: UTF8String;keySequence: UTF8String);
		procedure ShiftKeyDown();
		procedure ShiftKeyUp();
		procedure MetaKeyDown();
		procedure MetaKeyUp();
		procedure AltKeyDown();
		procedure AltKeyUp();
		procedure ControlKeyDown();
		procedure ControlKeyUp();
		procedure KeyDown(locator: UTF8String;keySequence: UTF8String);
		procedure KeyUp(locator: UTF8String;keySequence: UTF8String);
		procedure MouseOver(locator: UTF8String);
		procedure MouseOut(locator: UTF8String);
		procedure MouseDown(locator: UTF8String);
		procedure MouseDownRight(locator: UTF8String);
		procedure MouseDownAt(locator: UTF8String;coordString: UTF8String);
		procedure MouseDownRightAt(locator: UTF8String; coordString: UTF8String);
		procedure MouseUp(locator: UTF8String);
		procedure MouseUpRight(locator: UTF8String);
		procedure MouseUpAt(locator: UTF8String;coordString: UTF8String);
		procedure MouseUpRightAt(locator: UTF8String; coordString: UTF8String);
		procedure MouseMove(locator: UTF8String);
		procedure MouseMoveAt(locator: UTF8String;coordString: UTF8String);
		procedure Type_(locator: UTF8String;value: UTF8String);
		procedure TypeKeys(locator: UTF8String;value: UTF8String);
		procedure SetSpeed(value: UTF8String);
		function GetSpeed(): UTF8String;
		procedure Check(locator: UTF8String);
		procedure Uncheck(locator: UTF8String);
		procedure Select(selectLocator: UTF8String; optionLocator: UTF8String);
		procedure AddSelection(locator: UTF8String;optionLocator: UTF8String);
		procedure RemoveSelection(locator: UTF8String;optionLocator: UTF8String);
		procedure RemoveAllSelections(locator: UTF8String);
		procedure Submit(formLocator: UTF8String);
		procedure Open(url: UTF8String);
		procedure OpenWindow(url: UTF8String;windowID: UTF8String);
		procedure SelectWindow(windowID: UTF8String);
		procedure SelectPopUp(windowID: UTF8String);
    procedure DeselectPopUp();
		procedure SelectFrame(locator: UTF8String);
		function GetWhetherThisFrameMatchFrameExpression(currentFrameString: UTF8String;target: UTF8String): boolean;
		function GetWhetherThisWindowMatchWindowExpression(currentWindowString: UTF8String;target: UTF8String): boolean;
		procedure WaitForPopUp( windowID: UTF8String;timeout: UTF8String);
		procedure ChooseCancelOnNextConfirmation();
		procedure ChooseOkOnNextConfirmation();
		procedure AnswerOnNextPrompt(answer: UTF8String);
		procedure GoBack();
		procedure Refresh();
		procedure Close();
		function IsAlertPresent(): boolean;
		function IsPromptPresent(): boolean;
		function IsConfirmationPresent(): boolean;
		function GetAlert(): UTF8String;
		function GetConfirmation(): UTF8String;
		function GetPrompt(): UTF8String;
		function GetLocation(): UTF8String;
		function GetTitle(): UTF8String;
		function GetBodyText(): UTF8String;
		function GetValue(locator: UTF8String): UTF8String;
		function GetText(locator: UTF8String): UTF8String;
		procedure Highlight(locator: UTF8String);
		function GetEval(script: UTF8String): UTF8String;
		function IsChecked(locator: UTF8String): boolean;
		function GetTable(tableCellAddress: UTF8String): UTF8String;
		function GetSelectedLabels(selectLocator: UTF8String): ArrayOfUTF8String;
		function GetSelectedLabel(selectLocator: UTF8String): UTF8String;
		function GetSelectedValues(selectLocator: UTF8String): ArrayOfUTF8String;
		function GetSelectedValue(selectLocator: UTF8String): UTF8String;
		function GetSelectedIndexes(selectLocator: UTF8String): ArrayOfUTF8String;
		function GetSelectedIndex(selectLocator: UTF8String): UTF8String;
		function GetSelectedIds(selectLocator: UTF8String): ArrayOfUTF8String;
		function GetSelectedId(selectLocator: UTF8String): UTF8String;
		function IsSomethingSelected(selectLocator: UTF8String): boolean;
		function GetSelectOptions(selectLocator: UTF8String): ArrayOfUTF8String;
		function GetAttribute(selectLocator: UTF8String): UTF8String;
		function IsTextPresent(pattern: UTF8String): boolean;
		function IsElementPresent(locator: UTF8String): boolean;
		function IsVisible(locator: UTF8String): boolean;
		function IsEditable(locator: UTF8String): boolean;
		function GetAllButtons(): ArrayOfUTF8String;
		function GetAllLinks(): ArrayOfUTF8String;
		function GetAllFields(): ArrayOfUTF8String;
		function GetAttributeFromAllWindows(attributeName: UTF8String): ArrayOfUTF8String;
		procedure Dragdrop(locator: UTF8String; movementsString: UTF8String);
		procedure SetMouseSpeed(pixels: UTF8String);
		function GetMouseSpeed(): double;
		procedure DragAndDrop(locator: UTF8String;movementsString: UTF8String);
		procedure DragAndDropToObject(locatorOfObjectToBeDragged:UTF8String; locatorOfDragDestinationObject: UTF8String);
		procedure WindowFocus();
		procedure WindowMaximize();
		function GetAllWindowIds(): ArrayOfUTF8String;
		function GetAllWindowNames(): ArrayOfUTF8String;
		function GetAllWindowTitles(): ArrayOfUTF8String;
		function GetHtmlSource(): UTF8String;
		procedure SetCursorPosition(locator: UTF8String; position: UTF8String);
		function GetElementIndex(locator: UTF8String): double;
		function IsOrdered(locator1: UTF8String; locator2: UTF8String): boolean;
		function GetElementPositionLeft(locator: UTF8String): double;
		function GetElementPositionTop(locator: UTF8String): double;
		function GetElementWidth(locator: UTF8String): double;
		function GetElementHeight(locator: UTF8String): double;
		function GetCursorPosition(locator: UTF8String): double;
		function GetExpression(expression: UTF8String): UTF8String;
		function GetXpathCount(xpath: UTF8String): double;
		procedure AssignId(locator: UTF8String;  identifier: UTF8String);
		procedure AllowNativeXpath(allow: UTF8String);
		procedure IgnoreAttributesWithoutValue(ignore: UTF8String);
		procedure WaitForCondition(script: UTF8String; timeout: UTF8String);
		procedure SetTimeout(timeout: UTF8String);
		procedure WaitForPageToLoad(timeout: UTF8String);
		procedure WaitForFrameToLoad(frameAddress: UTF8String; timeout: UTF8String);
		function GetCookie():  UTF8String;
		function GetCookieByName(name: UTF8String):  UTF8String;
		function IsCookiePresent(name: UTF8String): boolean;
		procedure CreateCookie(nameValuePair: UTF8String; optionsString: UTF8String);
		procedure DeleteCookie(name: UTF8String; optionsString: UTF8String);
		procedure DeleteAllVisibleCookies();
		procedure SetBrowserLogLevel(logLevel: UTF8String);
		procedure RunScript(script: UTF8String);
		procedure AddLocationStrategy(strategyName: UTF8String; functionDefinition: UTF8String);
		procedure CaptureEntirePageScreenshot(filename: UTF8String; kwargs: UTF8String);
    procedure Rollup(rollupName: UTF8String; kwargs: UTF8String);
    procedure AddScript(scriptContent: UTF8String; scriptTagId: UTF8String);
    procedure RemoveScript(scriptTagId: UTF8String);
    procedure UseXpathLibrary(libraryName: UTF8String);   
		procedure SetContext(context: UTF8String);
		procedure AttachFile(fieldLocator: UTF8String; fileLocator: UTF8String);
		procedure CaptureScreenshot(filename: UTF8String);
    function CaptureScreenshotToString(): UTF8String;
    function CaptureEntirePageScreenshotToString(kwargs: UTF8String): UTF8String;
		procedure ShutDownSeleniumServer();
		function RetrieveLastRemoteControlLogs(): UTF8String;
		procedure KeyDownNative(keycode: UTF8String);
		procedure KeyUpNative(keycode: UTF8String);
		procedure KeyPressNative(keycode: UTF8String);
    procedure AddCustomRequestHeader(key: UTF8String; value: UTF8String);
    function CaptureNetworkTraffic(_type: UTF8String): UTF8String;
  end;

implementation

end.
